officemanagement/employee/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from employee import views as view

urlpatterns = [
   path('' , view.index , name='index'),
   path('add_employee/' , view.add_employee , name='add_employee'),
   path('remove_employee/' , view.remove_employee , name='remove_employee'),
   path('edit_employee/' , view.edit_employee , name='edit_employee'),



]

officemanagement/officemanagement/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

officemanagement/employee/models.py
from django.db import models

# Create your models here.


class Departments(models.Model):
	name = models.CharField(max_length=100)
	location = models.CharField(max_length=100)

	def __str__(self):
		return self.name


class Role(models.Model):
	name = models.CharField(max_length=100)
	description = models.CharField(max_length=100)
	def __str__(self): # we write this method to show the name of the role in the admin panel as we are not able to see it directly
		return self.name + ' - ' + self.description



class Employees(models.Model):
	name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	age = models.IntegerField()
	salary = models.IntegerField()
	department = models.ForeignKey(Departments, on_delete=models.CASCADE) # here we user CASCADE to delete the department if it is deleted
	position = models.ForeignKey(Role, on_delete=models.CASCADE)
	phone = models.CharField(max_length=100)
	hire_date = models.DateField()

	def __str__(self):
		return self.name + ' ' + self.last_name + ' - ' + self.position.name + ' - ' + self.department.name

officemanagement/employee/views.py
from django.shortcuts import render , redirect
from templates import  *
# from models import *

# Create your views here.


def index(request):
	return render(request, 'index.html')

def add_employee(request):
	if request.method == 'POST':

		name  = request.POST["name"]
		last_name = request.POST["last_name"]
		email = request.POST["email"]
		phone = request.POST["phone"]
		address = request.POST["address"]
		salary = request.POST["salary"]
		position = request.POST["position"]
		department = request.POST["department"]
		hire_date = request.POST["hire_date"]
		employee = Employees(name=name, last_name=last_name, email=email, phone=phone, address=address, salary=salary, position=position, department=department, hire_date=hire_date)
		employee.save()
	return render(request, 'add_employee.html')

def remove_employee(request):
	return render(request, 'remove_employee.html')

def edit_employee(request):
	return render(request, 'edit_employee.html')

officemanagement/templates/add_employee.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Hello, world!</title>
</head>

<body>


    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Officemanagement</h1>
                <p>Officemanagement is a web application for managing office tasks.</p>

            </div>
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="name">First Name</label>
                    <input type="text" value={{name}} class="form-control" id="id_name" name="name" placeholder="Enter First Name">
                </div>
                <div class="form-group">
                    <label for="last_name">Last Name</label>
                    <input type="text" value={{last_name}} class="form-control" id="id_last_name" name="last_name" placeholder="Enter Last Name">
                </div>
                <div class="form-group">
                    <label for="age">Age</label>
                    <input type="number" value={{age}} class="form-control" id="id_age" name="age" placeholder="Enter Age">
                </div>
                <div class="form-group">
                    <label for="salary">Salary</label>
                    <input type="number" value={{salary}} class="form-control" id="id_salary" name="salary" placeholder="Enter Salary">
                </div>
                <div class="form-group">
                    <label for="department">Department</label>
                    <input type="text" value={{department}} class="form-control" id="id_salary" name="salary" placeholder="Enter department">
                </div>
                <div class="form-group">
                    <label for="position">Position</label>
                    <input type="text" value={{position}} class="form-control" id="id_salary" name="salary" placeholder="Enter position">
                </div>
                <div class="form-group">
                    <label for="phone">Phone</label>
                    <input type="tel" value={{phone}} class="form-control" id="id_phone" name="phone" placeholder="Enter Phone Number">
                </div>
                <div class="form-group">
                    <label for="hire_date">Hire Date</label>
                    <input type="date" value={{hire_date}} class="form-control" id="id_hire_date" name="hire_date">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>


        </div>

    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


</body>

</html>

officemanagement/templates/index.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Hello, world!</title>
</head>

<body>


    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Officemanagement</h1>
                <p>Officemanagement is a web application for managing office tasks.</p>

            </div>
            <div class="container">
                <a href="add_employee/" role="button" class="btn btn-primary">
				Add Employee
			</a>
                <a href="/remove_employee" role="button" class="btn btn-primary">
				Remove Employee
			</a>
                <a href="/edit_employee" role="button" class="btn btn-primary">
				Edit Employee
			</a>
            </div>
        </div>

    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


</body>

</html>